# Database configuration props
spring.datasource:
                  url: jdbc:mysql://localhost:3306/ZonionsDB?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
                  username: root
                  password: root
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  initialization-mode: always

spring.jpa:
           properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
           hibernate.use-new-id-generator-mappings: false
           hibernate.ddl-auto: update


# Social login provider props
spring.security.oauth2.client.registration:
         google.clientId: 979041299011-7u15me5fbl4c8v8naq17b1vfm7sfjn7n.apps.googleusercontent.com
         google.clientSecret: Uw4s2gVBbV00u6-MdCgohEGp
         facebook.clientId: 3763231927105422
         facebook.clientSecret: d876d7dbfa58516278db27ff266b86f0


app.auth.tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
app.auth.tokenExpirationMsec: 864000000

app.oauth2.authorizedRedirectUris: http://localhost:4200/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect


#Rate Limiter Configurations
resilience4j.ratelimiter:
  instances:
    restaurantService:
      limitForPeriod: 2
      limitRefreshPeriod: 4s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


#Swagger Configuration
